version: "2"

services:
  chatapp:
    image: mashrooms:0.2
    build:
      context: ./chat
    network_mode: host
    environment:
      - MICROSOFT_APP_ID=${MICROSOFT_APP_ID}
      - MICROSOFT_APP_PASSWORD=${MICROSOFT_APP_PASSWORD}
      - debug=${debug}
      - count_accept=${count_accept}
    volumes:
      - ./chat:/srv/chatapp
    command: "python3 main.py"

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './tnlp.conf:/etc/nginx/conf.d/tnlp.conf:ro'
      - './certs:/var/tmp/certs'
      - './acme:/var/tmp/acme'
      - './builded_frontend:/var/tmp/builded_frontend'

    ports:
      - 80:80
